version: "2.1"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysql --host=mysql --user=laravel --password=laravel --database=laravel --execute=\"SELECT 1\";" ]
      interval: 5s
      timeout: 2s
      retries: 20
  booking-api:
    build:
      dockerfile: booking-api/Dockerfile
    container_name: booking-api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
  booking-sdk:
    build:
      dockerfile: booking-sdk/Dockerfile
    container_name: booking-sdk
    ports:
      - "8001:8001"
    depends_on:
      - booking-api